version: '3.7'
services:
  certification-exam-quizzer-toxiproxy:
    image: shopify/toxiproxy
    restart: always
    expose:
      - "22220"
  certification-exam-quizzer-toxiproxy-configurer:
    build:
      context: .
      dockerfile: Dockerfile-toxiproxy-configurer
    depends_on:
      - certification-exam-quizzer-toxiproxy
  certification-exam-quizzer-db:
    image: postgres
    restart: always
    volumes:
      - ./database/init.sh:/docker-entrypoint-initdb.d/0001-initialization.sh
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: quizzer
      POSTGRES_PASSWORD: quizzer
      ANON: web_anon
      AUTHENTICATOR: authenticator
#  certification-exam-quizzer-redis:
#    image: redis:alpine
#    restart: always
#    ports:
#      - 6379:6379

volumes:
  db-data:
    driver: local